'''title'''
__title__ = 'videodl'
'''description'''
__description__ = 'Videodl: A lightweight video downloader written in pure python'
'''url'''
__url__ = 'https://github.com/ac54u/videodl'
'''version'''
__version__ = '0.8.8'
'''author'''
__author__ = 'ac54u'
'''email'''
__email__ = 'charlesblwx@gmail.com'
'''license'''
__license__ = 'PolyForm-Noncommercial-1.0.0'
'''copyright'''
__copyright__ = 'A video downloader forked and maintained by ac54u.'